{% set name = "ctransformers" %}
{% set version = "0.2.27" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 25653d4be8a5ed4e2d3756544c1e9881bf95404be5371c3ed506a256c28663d5

build:
  script: {{ PYTHON }} -m pip install . -vv
  number: 1

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - cmake >=3.18
    - make
    - ninja    
    - scikit-build >=0.13
    - setuptools >=42
  host:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - cmake >=3.18
    - make
    - ninja
    - python
    - pip
    - scikit-build >=0.13
    - setuptools >=42
  run:
    - python
    - huggingface_hub
    - py-cpuinfo <10.0.0,>=9.0.0

test:
  imports:
    - ctransformers

about:
  home: https://github.com/marella/ctransformers
  summary: 'Python bindings for the Transformer models implemented in C/C++ using GGML library.'
  license: MIT
  license_family: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - raybellwaves
